# Generated by Django 3.2.3 on 2023-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20230407_0128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner'),
        ),
    ]
